# Generated by Django 3.0.5 on 2020-04-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_auto_20200429_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['description']},
        ),
        migrations.AddField(
            model_name='todo',
            name='tasklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='trelloapp.TaskList'),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('title', 'tasklist')},
        ),
    ]
