# Generated by Django 3.0.5 on 2020-04-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0003_auto_20200430_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together=set(),
        ),
    ]
