# Generated by Django 3.0.5 on 2020-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_auto_20200429_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_list',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
